### ISSUE TITLE
Too strong dependencies on non primitive data types, program cannot run on Netweaver developer edition

### ISSUE THREAD

**Issue by moniker23** [abapinho/abaK#23]
Type "FELDNAM" is unknown.
Type "SETID" is unknown.
Type "TLINE_T" is unknown.

![image](https://user-images.githubusercontent.com/49623891/56100342-dab9b180-5f17-11e9-8d4b-219a5492b9f9.png)

**Comment by nununo** [comment]
Hum... thank you @moniker23. Having an old ABAP version it is hard to anticipate what may or may nor work in more recent versions. I will push a correction hopefully tonight. Thanks!

**Comment by moniker23** [comment]
> Hum... thank you @moniker23. Having an old ABAP version it is hard to anticipate what may or may nor work in more recent versions. I will push a correction hopefully tonight. Thanks!

I don't have old ABAP version, it is almost the newest. Current version is 7.52, I have 7.51. Problem is more, that the development depends on certain components which are not in this Netweaver for ABAP. 

https://www.sap.com/developer/trials-downloads/additional-downloads/sap-netweaver-as-abap-developer-edition-sp01-7-52-15510.html

**Comment by nununo** [comment]
I meant to say that I (not you) am still using an old version :)

**Comment by moniker23** [comment]
sorry, now i understand :)

**Comment by nununo** [comment]
@moniker23 I believe this last PR removed the external dependencies you found to break your system. Would it be possible for you to test it again and let me know if this is still an issue?

**Comment by moniker23** [comment]
@nununo Sure, I am planning to retest everything, just didn't have time yesterday. Today I will retest. Thank you :)

**Comment by nununo** [comment]
Thanks @moniker23. Just don't be scared with the amount of objects that changed. What happend was: meanwhile I had subdivided the package into multiple sub-packages and abapGit included everything that moved to a different subpackage :)

Ideally I'd be doing one change per PR but this was not possible this time.

**Comment by moniker23** [comment]
Hi @nununo ,

still some types missing :)

![image](https://user-images.githubusercontent.com/49623891/56321735-96bceb80-6167-11e9-9804-141e1d5007eb.png)

Thanks

**Comment by sdfraga** [comment]
Hello @moniker23 ,

In which version of Netweaver are you?
In version 750 I can see that this elements are pretty old. 
Strange you don't have them.

![image](https://user-images.githubusercontent.com/16186872/56344498-e0d0bc00-61bd-11e9-960c-5a069f4c04f6.png)

![image](https://user-images.githubusercontent.com/16186872/56344523-ed551480-61bd-11e9-929d-117e2b9fe71a.png)

![image](https://user-images.githubusercontent.com/16186872/56344561-ff36b780-61bd-11e9-9b18-0fe4a385aae0.png)

**Comment by moniker23** [comment]
Hello @Sdfraga , I am using netweaver 7.51, but it is just ABAP stripped of almost all application functionality. It is a system which I can run at home.  So yes, those domains are pretty old, but probably connected with some application functionality. I

https://www.sap.com/developer/trials-downloads/additional-downloads/sap-netweaver-as-abap-developer-edition-sp01-7-52-15510.html

**Comment by sdfraga** [comment]
ah ok that's nice.
Just for curiosity what is your setup for running your personal Netweaver instance.
And do you suggest any tutorial/blog on how to install it?

Regarding your issue @nununo let's wait that @nununo changes the core of abaK and eliminates the dependencies.

**Comment by moniker23** [comment]
@Sdfraga my configuration is DELL XPS13 wit 16GB of RAM, but I think that you can run it even on 8GB with some virtual memory. I am running it in docker container, but you can run it also in linux in virtualbox or other VM software.  Tutorial for docker https://github.com/nzamani/sap-nw-abap-trial-docker

**Comment by nununo** [comment]
Hi @moniker23, 

1. Are you sure you're using the latest version (pushed last night)?
I'm intrigued because some of the errors you're reporting were already corrected in version 69f088e181a88bcdbbe27af00c1cc8db92d3df5a which I created last night:
- `ZCL_ABAK` doesn't have any reference to `FELDNAME` or `FELDNAM`. It was replaced by the new `ZABAK_FIELDNAME`.
- `ZCL_ABAK_SOURCE_SO10` doesn't have a reference to `TLINE_T`

2. You don't have data element `SETCLASS`
This class is using standard FM `G_SET_GET_ALL_VALUES` which accepts this data element. Can you tell me if you have this FM? If not, I'll have to come up with another way to fetch data from a SET. If yes, what is the data element of parameter `CLASS`?

Probably I'll have to setup a system like the one you have so that I can see these errors for myself. I won't be able to do that in the next days though.

Thanks again!

**Comment by moniker23** [comment]
@nununo  I was doing the pull thing for sure, but I am not that much expereinced with abapgit so maybe I commited some mistake. I will recheck that today after working hours and write the results. Thank you, too :)

**Comment by nununo** [comment]
@moniker23 if the normal PULL doesn't work maybe you have to do a RESET LOCAL (in ADVANCED menu).

**Comment by sdfraga** [comment]
Hi,

Just installed abaK in my personal SAP CAL instance running on GCP and I have the same issues than @moniker23 

![abaK](https://user-images.githubusercontent.com/16186872/56429430-190df280-62c3-11e9-8436-a6e6eab69fd8.PNG)

**Comment by nununo** [comment]
Hi @moniker23 unfortunately I wasn't able to replicate your environment so I couldn't find and fix all your problems. Fortunately @Sdfraga seems to have been able to nail it (thank you!). I hope this is it. Do let me know so that we can close this issue.

Indeed, like @Sdfraga said, the SET, being part of the FI module, has no place in a generic tool. I'll either abandon it or ship it as an optional addon.

**Comment by nununo** [comment]
I cannot test it but I will assume the changes done by @Sdfraga solved this issue. Please feel free to reopen it if you find that there are still problems @moniker23. Thanks.
